kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  environment:
    USERNAME:
      from_secret: docker_username
  commands:
  - echo hello $USERNAME > .env
  - cat .env